### PR TITLE
few fixes

### PR DESCRIPTION
**Pull request by anthonydahanne**
I'll let you review the validity of those very small changes @aurbroszniowski 
I could run this example against a 1 node OSS cluster, that worked fine, thanks.
I'd need your help to better understand the results though :-)

Also, I'm not sure to understand how rainfall uses the FakerGenerator : does it create a new Faker instance for each put ? which method does it call to get the value to put in cache ?
I probably should have a better look...
thanks @aurbroszniowski

### CODE REVIEW

**Comment by aurbroszniowski** [comment]
can you change your PR to have only those two commits:
-   cache size is no longer required    9de3cd1
-   add slf4j logger impl

the two other issues come from the fact that i forgot  to add the snapshot nexus location in the pom

**Comment by aurbroszniowski** [comment]
actually let me include your change in my next commit, it's a trivial change, no need to spend time tweaking this PR

**Comment by anthonydahanne** [comment]
Sure no problem, you can bounce the PR and get the commits from my fork

**Comment by aurbroszniowski** [comment]
done

**Pull request closed without merging**
